services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"
